### ISSUE TITLE
Apply for dataset downloading.

### ISSUE THREAD

**Issue by Nicozwy** [ICTMCG/FakeSV#10]
Great work. I have signed [this agreement](https://drive.google.com/file/d/1Ozj5OOYoDYnDznDLAECBvlGIDtyGl6Vz) and sent the signed copy to [qipeng@ict.ac.cn](mailto:qipeng@ict.ac.cn) this morning. 

Looking forward to hearing from you!

Thank you very much!

**Comment by Nicozwy** [comment]
I also sent the signed copy to [pengqi.qp@gmail.com](mailto:pengqi.qp@gmail.com) and caojuan@ict.ac.cn. If there are any discrepancies that do not meet the requirements, please inform me of the reasons. Thank you very much. @MischaQI @sheng-qiang

**Comment by MischaQI** [comment]
I have received your three emails and replied the dataset downloading link. Plz check your spam folder. Thanks for your attention!

**Comment by Nicozwy** [comment]
> I have received your three emails and replied the dataset downloading link. Plz check your spam folder. Thanks for your attention!

Thank you for the response. I checked the spam folder but couldn't find any emails. So could you send the downloading link to my another mailbox as requested?

**Comment by Nicozwy** [comment]
![微信图片_20231118174810](https://github.com/ICTMCG/FakeSV/assets/19528731/b0e01eeb-7d47-4f9f-9a92-9748ce850ab3)


> > I have received your three emails and replied the dataset downloading link. Plz check your spam folder. Thanks for your attention!
> 
> Thank you for the response. I checked the spam folder but couldn't find any emails. So could you send the downloading link to my another mailbox as requested?

![微信图片_20231118174810](https://github.com/ICTMCG/FakeSV/assets/19528731/6a2e41e2-251b-4a3f-b9e5-535203c2a38e)

**Comment by Nicozwy** [comment]
Could you reply to the email again？@MischaQI
