### ISSUE TITLE
Issues on Dataset downloading: I have been approved but have not received the download link.

### ISSUE THREAD

**Issue by Nicozwy** [ICTMCG/FakeSV#11]
Sorry for the disturbance.
I have been approved but have not received the download link. #10 . I am sure that there have been no emails in my spam folder until now. 

What should I do to download the dataset?

**Comment by MischaQI** [comment]
Hi, I have re-sent the download link to the new email you provided. Please check it. Thanks!

**Comment by Nicozwy** [comment]
Got it. Thanks for your prompt reply.
