### ISSUE TITLE
problem in dataloader.py

### ISSUE THREAD

**Issue by DimPenCHEN** [ICTMCG/FakeSV#13]
I have solved the data problems(I think),but I found that the file "dataloader.py" using the "label" key in data.json which is no in my data.json 
        **self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk**
![361e5823f04fd2d2e66eb7fff9493ae](https://github.com/ICTMCG/FakeSV/assets/120781027/813ace40-bfaf-460f-9397-b7a45ae69264)

BTW, I haven't obatined the data directory **"vids"** and **"ptvgg19_frame_thumb"**which aren't mentioned in the public dataset.
I wonder how to sovle this problem in **dataloader.py** TwT

**Comment by pp-jia** [comment]
How did you obtain the Dataset? Did you crawl it based on **data.json**? @DimPenCHEN

**Comment by DimPenCHEN** [comment]
@pp-jia https://huggingface.co/datasets/MischaQI/FakeSV/tree/main
This link is available to obtain the data you need

**Comment by pp-jia** [comment]
Thanks, you can contact me via the email address on my homepage. @DimPenCHEN

**Comment by TODO-main** [comment]
> I have solved the data problems(I think),but I found that the file "dataloader.py" using the "label" key in data.json which is no in my data.json **self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk** ![361e5823f04fd2d2e66eb7fff9493ae](https://private-user-images.githubusercontent.com/120781027/293881939-813ace40-bfaf-460f-9397-b7a45ae69264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTk4NzQsIm5iZiI6MTcxMTcxOTU3NCwicGF0aCI6Ii8xMjA3ODEwMjcvMjkzODgxOTM5LTgxM2FjZTQwLWJmYWYtNDYwZi05Mzk3LWI3YTQ1YWU2OTI2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMzM5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzdiOTkzYTZiN2IwNjJlODM4NTcyY2Q2OWMyNDVlZmM2NDQ0ZmU3MWMyNzUzMjhlNmUxNTM5YzEzMGZkN2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xldfAC3uX3dNtGYjMwfuBX2CMqOz4bRmROnSfZjvj8c)
> 
> BTW, I haven't obatined the data directory **"vids"** and **"ptvgg19_frame_thumb"**which aren't mentioned in the public dataset. I wonder how to sovle this problem in **dataloader.py** TwT

I have the same problem, have you solved this problem

**Comment by TODO-main** [comment]
> > I have solved the data problems(I think),but I found that the file "dataloader.py" using the "label" key in data.json which is no in my data.json **self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk** ![361e5823f04fd2d2e66eb7fff9493ae](https://private-user-images.githubusercontent.com/120781027/293881939-813ace40-bfaf-460f-9397-b7a45ae69264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTk4NzQsIm5iZiI6MTcxMTcxOTU3NCwicGF0aCI6Ii8xMjA3ODEwMjcvMjkzODgxOTM5LTgxM2FjZTQwLWJmYWYtNDYwZi05Mzk3LWI3YTQ1YWU2OTI2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMzM5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzdiOTkzYTZiN2IwNjJlODM4NTcyY2Q2OWMyNDVlZmM2NDQ0ZmU3MWMyNzUzMjhlNmUxNTM5YzEzMGZkN2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xldfAC3uX3dNtGYjMwfuBX2CMqOz4bRmROnSfZjvj8c)
> > BTW, I haven't obatined the data directory **"vids"** and **"ptvgg19_frame_thumb"**which aren't mentioned in the public dataset. I wonder how to sovle this problem in **dataloader.py** TwT
> 
> I have the same problem, have you solved this problem

There is no ”lable“ attribute in the supplied "data.json" file

**Comment by andr2w** [comment]
The data.json file does not contain the 'label' column.
My way to solve this problem is to modify the `SVFENDDataset` as follows:

```Python
replace_values = {'辟谣': 2, '假': 1, '真':0}
self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
 #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk

```

**Comment by andr2w** [comment]
> The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> 
> ```python
> replace_values = {'辟谣': 2, '假': 1, '真':0}
> self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
>  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> ```

If you follow the above, be sure to modify the following code into
```python
label = 0 if item['annotation'] == '真' else 1
```
to
```python
label = 0 if item['annotation'] == 0 else  1
```
Otherwise, there will be a significant error during the training phase.

**Comment by TODO-main** [comment]
> > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > ```python
> > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > ```
> 
> If you follow the above, be sure to modify the following code into
> 
> ```python
> label = 0 if item['annotation'] == '真' else 1
> ```
> 
> to
> 
> ```python
> label = 0 if item['annotation'] == 0 else  1
> ```
> 
> Otherwise, there will be a significant error during the training phase.

Thank you for your reply, which gave me a good solution to this problem. However, after solving this problem, I met a new problem. I wonder if you have also met the same problem?
![image](https://github.com/ICTMCG/FakeSV/assets/116880314/6dcc1093-ebe5-43a4-91f1-faafa7110d10)

**Comment by zsd-1** [comment]
Hi. Could someone please help me identify the files in the ‘data’ directory and explain how they are organized?

**Comment by MischaQI** [comment]
> > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > ```python
> > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > ```
> > 
> > 
> > If you follow the above, be sure to modify the following code into
> > ```python
> > label = 0 if item['annotation'] == '真' else 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```python
> > label = 0 if item['annotation'] == 0 else  1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Otherwise, there will be a significant error during the training phase.
> 
> Thank you for your reply, which gave me a good solution to this problem. However, after solving this problem, I met a new problem. I wonder if you have also met the same problem? ![image](https://private-user-images.githubusercontent.com/116880314/320835262-6dcc1093-ebe5-43a4-91f1-faafa7110d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzgzNTcsIm5iZiI6MTcxNzkzODA1NywicGF0aCI6Ii8xMTY4ODAzMTQvMzIwODM1MjYyLTZkY2MxMDkzLWViZTUtNDNhNC05MWYxLWZhYWZhNzExMGQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMzAwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWQ5ZTJhOWMwYTg5ZDMwNDA5NjIwYmY1MjA5ODgxMWQzZTg1YWZmNjAzODI5OWI4ZDRkYzZkMmMzYTMwYTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i3sm-Wp2SJrq4tLGRKVeL5mh4mFwkJxt77OYXh4gl2k)

Hi, you could obtain the files you mentioned by [this way](https://github.com/ICTMCG/FakeSV/issues/8#issuecomment-2042480427).

**Comment by SeinCore** [comment]
> > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > ```python
> > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > ```
> 
> If you follow the above, be sure to modify the following code into
> 
> ```python
> label = 0 if item['annotation'] == '真' else 1
> ```
> 
> to
> 
> ```python
> label = 0 if item['annotation'] == 0 else  1
> ```
> 
> Otherwise, there will be a significant error during the training phase.



> The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> 
> ```python
> replace_values = {'辟谣': 2, '假': 1, '真':0}
> self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
>  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> ```

Thank you so much for your helpful suggestion. I’ve noticed that the "data.json" file provided doesn’t include the "keywords" and "ocr" attributes. I was wondering how you handled this issue? Any guidance would be greatly appreciated.

**Comment by Yani1214** [comment]
> > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > ```python
> > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > ```
> > 
> > 
> > If you follow the above, be sure to modify the following code into
> > ```python
> > label = 0 if item['annotation'] == '真' else 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```python
> > label = 0 if item['annotation'] == 0 else  1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Otherwise, there will be a significant error during the training phase.
> 
> > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > ```python
> > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > ```
> 
> Thank you so much for your helpful suggestion. I’ve noticed that the "data.json" file provided doesn’t include the "keywords" and "ocr" attributes. I was wondering how you handled this issue? Any guidance would be greatly appreciated.

Hello, have you solved this problem? I also encountered the same problem when reproducing the paper (data.json does not have "description" and "ocr" attributes). I would be grateful if you can reply.  @fuxiaoiii

**Comment by SeinCore** [comment]
> > > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > > ```python
> > > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > > ```
> > > 
> > > 
> > > If you follow the above, be sure to modify the following code into
> > > ```python
> > > label = 0 if item['annotation'] == '真' else 1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to
> > > ```python
> > > label = 0 if item['annotation'] == 0 else  1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Otherwise, there will be a significant error during the training phase.
> > 
> > 
> > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > ```python
> > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > ```
> > 
> > 
> > Thank you so much for your helpful suggestion. I’ve noticed that the "data.json" file provided doesn’t include the "keywords" and "ocr" attributes. I was wondering how you handled this issue? Any guidance would be greatly appreciated.
> 
> Hello, have you solved this problem? I also encountered the same problem when reproducing the paper (data.json does not have "description" and "ocr" attributes). I would be grateful if you can reply. @fuxiaoiii

Hi, you need to contact the owner to get the dataset, which includes the "description" and "ocr" attributes in a file.

**Comment by Yani1214** [comment]
> > > > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > > > ```python
> > > > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > > > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > > > ```
> > > > 
> > > > 
> > > > If you follow the above, be sure to modify the following code into
> > > > ```python
> > > > label = 0 if item['annotation'] == '真' else 1
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > to
> > > > ```python
> > > > label = 0 if item['annotation'] == 0 else  1
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Otherwise, there will be a significant error during the training phase.
> > > 
> > > 
> > > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > > ```python
> > > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > > ```
> > > 
> > > 
> > > Thank you so much for your helpful suggestion. I’ve noticed that the "data.json" file provided doesn’t include the "keywords" and "ocr" attributes. I was wondering how you handled this issue? Any guidance would be greatly appreciated.
> > 
> > 
> > Hello, have you solved this problem? I also encountered the same problem when reproducing the paper (data.json does not have "description" and "ocr" attributes). I would be grateful if you can reply. @fuxiaoiii
> 
> Hi, you need to contact the owner to get the dataset, which includes the "description" and "ocr" attributes in a file.

Thank you very much for your help!

**Comment by qishenghu** [comment]
> > > > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > > > ```python
> > > > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > > > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > > > ```
> > > > 
> > > > 
> > > > If you follow the above, be sure to modify the following code into
> > > > ```python
> > > > label = 0 if item['annotation'] == '真' else 1
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > to
> > > > ```python
> > > > label = 0 if item['annotation'] == 0 else  1
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Otherwise, there will be a significant error during the training phase.
> > > 
> > > 
> > > > The data.json file does not contain the 'label' column. My way to solve this problem is to modify the `SVFENDDataset` as follows:
> > > > ```python
> > > > replace_values = {'辟谣': 2, '假': 1, '真':0}
> > > > self.data_complete['annotation'] = self.data_complete['annotation'].replace(replace_values)
> > > > self.data_complete = self.data_complete[self.data_complete['annotation']!=2]
> > > >  #self.data_complete = self.data_complete[self.data_complete['label']!=2] # label: 0-real, 1-fake, 2-debunk
> > > > ```
> > > 
> > > 
> > > Thank you so much for your helpful suggestion. I’ve noticed that the "data.json" file provided doesn’t include the "keywords" and "ocr" attributes. I was wondering how you handled this issue? Any guidance would be greatly appreciated.
> > 
> > 
> > Hello, have you solved this problem? I also encountered the same problem when reproducing the paper (data.json does not have "description" and "ocr" attributes). I would be grateful if you can reply. @fuxiaoiii
> 
> Hi, you need to contact the owner to get the dataset, which includes the "description" and "ocr" attributes in a file.

Hi, may I ask is the 'description' field contained in the 'data_complete.json' file? I seem to unable to find 'description' field in the data_complete.json file provided, but am able to find 'ocr'. @fuxiaoiii @MischaQI
