### ISSUE TITLE
太有趣了，我毕设正好也想做这个苦于没有视频数据集

### ISSUE THREAD

**Issue by forAlgorithm** [ICTMCG/FakeSV#2]
！！！！深夜激动，对了我还不知道作者是学长还是学姐，请问你们课题组招客座学生嘛？我想尝试图神经网络在社交媒体领域的运用呢

**Comment by MischaQI** [comment]
> ！！！！深夜激动，对了我还不知道作者是学长还是学姐，请问你们课题组招客座学生嘛？我想尝试图神经网络在社交媒体领域的运用呢

感谢关注:) 
可以发送简历给[课题组老师](http://www.ict.cas.cn/sourcedb_2018_ict_cas/cn/jssrck/201011/t20101123_3028158.html)询问是否有合作机会
