### ISSUE TITLE
No such file or directory: './data/dict_vid_audioconvfea.pkl'

### ISSUE THREAD

**Issue by Lipapaldl** [ICTMCG/FakeSV#20]
No such file or directory: './data/dict_vid_audioconvfea.pkl'
how can I get it?

**Comment by Lipapaldl** [comment]
How to find the file "vid_fold_no_xxx.txt"?

**Comment by sheng-qiang** [comment]
You may refer to https://github.com/ICTMCG/FakeSV/issues/3

**Comment by SeinCore** [comment]
May I ask if you have resolved this issue? If so, would you be able to share how you solved it? @Lipapaldl

**Comment by MischaQI** [comment]
> May I ask if you have resolved this issue? If so, would you be able to share how you solved it? @Lipapaldl

If you're referring to the question about the file "vid_fold_no_xxx.txt", you can refer to https://github.com/ICTMCG/FakeSV/issues/8#issuecomment-2042480427

**Comment by SeinCore** [comment]
> > May I ask if you have resolved this issue? If so, would you be able to share how you solved it? @Lipapaldl
> 
> If you're referring to the question about the file "vid_fold_no_xxx.txt", you can refer to [#8 (comment)](https://github.com/ICTMCG/FakeSV/issues/8#issuecomment-2042480427)

Thank you for your response. I have resolved the issue. Additionally, I have sent the signed agreement to the specified email address to request access to the dataset, but I haven’t received a reply yet. Could you let me know if more details are needed or if there might be another reason for the delay?

**Comment by MischaQI** [comment]
> > > May I ask if you have resolved this issue? If so, would you be able to share how you solved it? @Lipapaldl
> > 
> > 
> > If you're referring to the question about the file "vid_fold_no_xxx.txt", you can refer to [#8 (comment)](https://github.com/ICTMCG/FakeSV/issues/8#issuecomment-2042480427)
> 
> Thank you for your response. I have resolved the issue. Additionally, I have sent the signed agreement to the specified email address to request access to the dataset, but I haven’t received a reply yet. Could you let me know if more details are needed or if there might be another reason for the delay?

I have checked my email box but didn't find your email. Do you mind sending it again to pengqi.qp@gmail.com? Thanks.

**Comment by SeinCore** [comment]
> > > > May I ask if you have resolved this issue? If so, would you be able to share how you solved it? @Lipapaldl
> > > 
> > > 
> > > If you're referring to the question about the file "vid_fold_no_xxx.txt", you can refer to [#8 (comment)](https://github.com/ICTMCG/FakeSV/issues/8#issuecomment-2042480427)
> > 
> > 
> > Thank you for your response. I have resolved the issue. Additionally, I have sent the signed agreement to the specified email address to request access to the dataset, but I haven’t received a reply yet. Could you let me know if more details are needed or if there might be another reason for the delay?
> 
> I have checked my email box but didn't find your email. Do you mind sending it again to [pengqi.qp@gmail.com](mailto:pengqi.qp@gmail.com)? Thanks.

I received your email this morning. Thank you very much!
