### ISSUE TITLE
How to get `dict_vid_audioconvfea.pkl`

### ISSUE THREAD

**Issue by XEric7** [ICTMCG/FakeSV#3]
I've read your code and found that it needs a file called [dict_vid_audioconvfea.pkl](https://github.com/ICTMCG/FakeSV/blob/main/code/utils/dataloader.py#L37). I also read your readme.md file about data processing but I'm still unsure how to convert a video in your dataset into this file.
Could you please provide some code or articles for guidance?

**Comment by MischaQI** [comment]
You can use open-source tools such as moviepy to split the audio from video. And then refer to [this code](https://raw.githubusercontent.com/ICTMCG/FakeSV/main/code/utils/vggish_modified.py) to obtain the audio convolutional features.

**Comment by Lipapaldl** [comment]
udio features for video 6863761687258959115 not found.
Audio features for video 6777377636827041038 not found.
Audio features for video 6890422257261268232 not found.
Audio features for video 7027859325582396702 not found.
Audio features for video 7013931633732488460 not found.
Audio features for video 6787632205754633487 not found.
Audio features for video 6862983978555641096 not found.
Audio features for video 6873756007982583051 not found. Why？
