### ISSUE TITLE
Question about Reproduction experiment 

### ISSUE THREAD

**Issue by whitebabycat** [ICTMCG/FakeSV#4]
In the process of repeating the experiment, the following doubts were found
1: No steps, such as the command line.
2: The process of data processing is not clear enough, as if the video needs to be manually processed by other plug-ins? What are the specific parameters? Can the pre-processed data set be uploaded for the convenience of experiment
3.How did you get the file opened on line 37 in the picture
![image](https://user-images.githubusercontent.com/65153370/235301562-d917b704-88f2-461b-ba0a-f896bb12a9cf.png)

**Comment by Aichiniuroumian** [comment]
Have you reproduced this code successfully?

**Comment by SleeplessBegonia** [comment]
Have you reproduced this code successfully?

**Comment by MischaQI** [comment]
Thank you for your attention. We have released the [pre-extracted features and checkpoints](https://huggingface.co/datasets/MischaQI/FakeSV/tree/main).
