### ISSUE TITLE
请问可以上传所需的文件吗？

### ISSUE THREAD

**Issue by chenshu2000** [ICTMCG/FakeSV#5]
不是很清楚代码里的一些文件是什么，请问可以上传以下的文件吗？
dict_vid_audioconvfea.pkl
./ptvgg19_frames/
./c3d/
stopwords.txt
./ptvgg19_frame_thumb/
./caption_w2v_pad%s.pkl/
./vgg19_result%s.pkl/
./asr_w2v+mfcc%s.pkl/

**Comment by SleeplessBegonia** [comment]
me too...do u know how to get dict_vid_audioconvfea.pkl?

**Comment by MischaQI** [comment]
Thank you for your attention. We have released the [pre-extracted features and checkpoints](https://huggingface.co/datasets/MischaQI/FakeSV/tree/main).

**Comment by TODO-main** [comment]
> 不是很清楚代码里的一些文件是什么，请问可以上传以下的文件吗？ dict_vid_audioconvfea.pkl ./ptvgg19_frames/ ./c3d/ stopwords.txt ./ptvgg19_frame_thumb/ ./caption_w2v_pad%s.pkl/ ./vgg19_result%s.pkl/ ./asr_w2v+mfcc%s.pkl/

哈喽，你有获得完整的文件吗，我发现提供的内容还是缺少data.json以及vid还有ptvgg19_frame_thumb的内容出现报错的情况
![image](https://github.com/ICTMCG/FakeSV/assets/116880314/359e0a72-54d4-4287-92dd-1c4859478acb)

**Comment by Yani1214** [comment]
> > 不是很清楚代码里的一些文件是什么，请问可以上传以下的文件吗？ dict_vid_audioconvfea.pkl ./ptvgg19_frames/ ./c3d/ stopwords.txt ./ptvgg19_frame_thumb/ ./caption_w2v_pad%s.pkl/ ./vgg19_result%s.pkl/ ./asr_w2v+mfcc%s.pkl/
> 
> 哈喽，你有获得完整的文件吗，我发现提供的内容还是缺少data.json以及vid还有ptvgg19_frame_thumb的内容出现报错的情况 ![image](https://private-user-images.githubusercontent.com/116880314/318252889-359e0a72-54d4-4287-92dd-1c4859478acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MjMyNTUsIm5iZiI6MTczNjkyMjk1NSwicGF0aCI6Ii8xMTY4ODAzMTQvMzE4MjUyODg5LTM1OWUwYTcyLTU0ZDQtNDI4Ny05MmRkLTFjNDg1OTQ3OGFjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQwNjM1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzMxMDBhMDhkNzYyZmNjMmMxODI0M2VhOTAxM2FjNDljM2NhOThhNDg2NGU2OGZhY2ZkMDYwOGRhMzY5M2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sTJrJqhu5B3lq0NA6ZVmBzYX-a45qpuQZdrBv_aVD9Y)

Hello, have you resolved the issue with the missing ptvgg19_frame_thumb?

**Comment by Yani1214** [comment]
> > 不是很清楚代码里的一些文件是什么，请问可以上传以下的文件吗？ dict_vid_audioconvfea.pkl ./ptvgg19_frames/ ./c3d/ stopwords.txt ./ptvgg19_frame_thumb/ ./caption_w2v_pad%s.pkl/ ./vgg19_result%s.pkl/ ./asr_w2v+mfcc%s.pkl/
> 
> 哈喽，你有获得完整的文件吗，我发现提供的内容还是缺少data.json以及vid还有ptvgg19_frame_thumb的内容出现报错的情况 ![image](https://github.com/ICTMCG/FakeSV/assets/116880314/359e0a72-54d4-4287-92dd-1c4859478acb)

Hello, have you resolved the issue with the missing ptvgg19_frame_thumb? @TODO-main
