### ISSUE TITLE
An excellent work! Regarding the code reproduction there are a couple of questions I would appreciate if you could answer.

### ISSUE THREAD

**Issue by Aichiniuroumian** [ICTMCG/FakeSV#6]
An excellent work!  Regarding the code reproduction there are a couple of questions I would appreciate if you could answer.

1）Is it convenient to disclose the individual modal features information extracted in the paper?
2）Is it convenient to provide more specific documentation to guide users to train or test the model?
3）What are your experimental hardware conditions? For example, what is the GPU model and what is the memory?
4）Is it convenient for you to disclose the weights of the trained model for comparison with your results?

Looking forward to your reply soon, thanks~! (●'◡'●)

**Comment by MischaQI** [comment]
Thank you for your attention. We have released the [pre-extracted features and checkpoints](https://huggingface.co/datasets/MischaQI/FakeSV/tree/main). Experiments are conducted on 1 V100 (32GB).  You can open a new issue if you encounter any problems in training/testing the models.
