### ISSUE TITLE
Question about dataset downloads

### ISSUE THREAD

**Issue by Bear879** [ICTMCG/FakeSV#7]
Very great paper. The paper states that the dataset is available in github, but I didn't find a way to download the raw data, only the id and the cut of the dataset. How can I download the raw dataset? Looking forward to your reply.

**Comment by Bear879** [comment]
There was no response to the email sent requesting access to the database. If it doesn't meet the requirements, please tell me the reason, thank you!

**Comment by MischaQI** [comment]
I'm sorry but I didn't see any unread emails about the dataset application. Would you mind resending the application to pengqi.qp@gmail.com?

**Comment by Nicozwy** [comment]
@Bear879 Have you got the dataset?
