### ISSUE TITLE
vid_fold_no_1.txt--vid_fold_no_5.txt

### ISSUE THREAD

**Issue by Aichiniuroumian** [ICTMCG/FakeSV#8]
Hi, Peng:
Thank you very much for sharing the withholding feature file. However, in the process of running the code, I encountered the following problems: There is a missing vid_fold_no_1.txt--vid_fold_no_5.txt in line 340 of run.py. I tried to generate the corresponding file myself.
But when I run the program, The error message indicates that 6800188418136493320,7049558892765891876,6790239252056771840,7019892562517429512,6814409751523233035 and other audio feature files cannot be found.
I don't know if there is any problem with the file I generated. Could you please share the following vid_fold_no_1.txt--vid_fold_no_5.txt? Thank you very much~

**Comment by pp-jia** [comment]
@Aichiniuroumian How did you obtain the Dataset? Did you crawl it based on data.json?

**Comment by DimPenCHEN** [comment]
these files are for training, we can't generate it by ourselves TwT.
Have you ever obtained these file?

**Comment by andr2w** [comment]
My solution:

Under the `./dataset/data-split/event/` folder, there are a total of five fold data samples.
`vid_fold_no_1.txt` is the other four folds combined together, e.g., `vid_fold_2.txt + ... + vid_fold_5.txt`.

**Comment by zsd-1** [comment]
> My solution:
> 
> Under the `./dataset/data-split/event/` folder, there are a total of five fold data samples. `vid_fold_no_1.txt` is the other four folds combined together, e.g., `vid_fold_2.txt + ... + vid_fold_5.txt`.

Could you please help me identify the files in the ‘data’ directory and how they are organized?
