### ISSUE TITLE
Issue on dataset downloading 

### ISSUE THREAD

**Issue by vivly** [ICTMCG/FakeSV#9]
The dataset mentioned in the paper is very interesting. I have completed the application form as instructed in the README file and submitted it to the designated email address. However, I have not received any response in the past week. If there are any discrepancies that do not meet the requirements, please inform me of the reasons. Thank you very much.

**Comment by MischaQI** [comment]
Sorry that I found it in the spam folder. I have already replied. Thank you for your attention.

**Comment by Nicozwy** [comment]
@MischaQI I have also applied for the dataset download. I look forward to hearing from you. Thank you very much.

**Comment by Nicozwy** [comment]
Have you got the dataset? @vivly
